# Generated by Django 5.2.9 on 2025-12-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.staffmember', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment', verbose_name='Cita'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_datetime', 'status'], name='appointment_start_d_465163_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'status'], name='appointment_client__c919d1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['staff', 'start_datetime'], name='appointment_staff_i_b10e5e_idx'),
        ),
    ]
