# Generated by Django 5.2.9 on 2026-05-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffmember_calendar_color'),
        ('appointments', '0003_service_snapshot_and_set_null'),
        ('core', '0007_add_cover_position'),
        ('services', '0002_add_image_to_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('preferred_date', models.DateField(verbose_name='Fecha preferida')),
                ('preferred_time_start', models.TimeField(blank=True, null=True, verbose_name='Hora preferida desde')),
                ('preferred_time_end', models.TimeField(blank=True, null=True, verbose_name='Hora preferida hasta')),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('notified', 'Notificado'), ('claimed', 'Reservó'), ('expired', 'Expiró sin reservar'), ('cancelled', 'Cancelado')], default='waiting', max_length=20, verbose_name='Estado')),
                ('claim_token', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Token de reclamo')),
                ('claim_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expira')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificado el')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reservó el')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.branch', verbose_name='Sucursal')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='accounts.client', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='services.service', verbose_name='Servicio')),
                ('staff', models.ForeignKey(blank=True, help_text='Null si el cliente acepta cualquier profesional disponible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='accounts.staffmember', verbose_name='Profesional preferido')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Listas de espera',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['branch', 'service', 'status', 'preferred_date'], name='appointment_branch__19631c_idx'), models.Index(fields=['phone_number', 'status'], name='appointment_phone_n_b39510_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('branch', 'service', 'phone_number', 'preferred_date'), name='unique_active_waitlist_entry')],
            },
        ),
    ]
