# Generated by Django 5.2.9 on 2026-05-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffmember_calendar_color'),
        ('appointments', '0004_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='notified_for_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del slot ofrecido'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='notified_for_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.staffmember', verbose_name='Profesional del slot ofrecido'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='notified_for_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio del slot ofrecido'),
        ),
    ]
