# Generated by Django 5.2.9 on 2026-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_waitlistentry_notified_for_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto cobrado al reservar (snapshot del % del precio).', max_digits=10, null=True, verbose_name='Monto del depósito'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_charge_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID del charge Culqi'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Depósito pagado el'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Depósito reembolsado el'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_status',
            field=models.CharField(choices=[('not_required', 'No requerido'), ('paid', 'Pagado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='not_required', max_length=20, verbose_name='Estado del depósito'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Esperando pago'), ('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
