# Generated by Django 5.2.9 on 2025-12-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], default='U', help_text='Para quién está dirigido el servicio', max_length=1, verbose_name='Género')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del servicio en esta sucursal', max_digits=10, verbose_name='Precio')),
                ('buffer_time_before', models.PositiveIntegerField(default=0, help_text='Tiempo de preparación antes del servicio', verbose_name='Tiempo buffer antes (minutos)')),
                ('buffer_time_after', models.PositiveIntegerField(default=0, help_text='Tiempo de limpieza después del servicio', verbose_name='Tiempo buffer después (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.branch', verbose_name='Sucursal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio personalizado')),
                ('custom_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración personalizada (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_providers', to='services.service', verbose_name='Servicio')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='accounts.staffmember', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Servicio del Profesional',
                'verbose_name_plural': 'Servicios de Profesionales',
                'unique_together': {('staff', 'service')},
            },
        ),
    ]
