# Generated by Django 5.2.9 on 2025-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa del servicio', null=True, upload_to='services/', verbose_name='Imagen'),
        ),
    ]
