# Generated by Django 5.2.9 on 2025-12-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('primary_color', models.CharField(default='#1a1a2e', help_text='Color hexadecimal (ej: #1a1a2e)', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#c9a227', help_text='Color hexadecimal (ej: #c9a227)', max_length=7, verbose_name='Color secundario')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='businesses/covers/', verbose_name='Imagen de portada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='branches/covers/', verbose_name='Imagen de portada')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('address_reference', models.CharField(blank=True, help_text='Ej: Frente al parque, 2do piso', max_length=200, verbose_name='Referencia')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('city', models.CharField(default='Lima', max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(default='Perú', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('timezone', models.CharField(default='America/Lima', max_length=50, verbose_name='Zona horaria')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sucursal principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['business', 'name'],
                'unique_together': {('business', 'slug')},
            },
        ),
    ]
