# Generated by Django 5.2.9 on 2025-12-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default='19:00', verbose_name='Hora de cierre'),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(default='09:00', verbose_name='Hora de apertura'),
        ),
    ]
