# Generated by Django 5.2.9 on 2025-12-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_closing_time_branch_opening_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recomendado: 800x600px o proporción 4:3', upload_to='branches/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, help_text='Descripción opcional de la foto', max_length=200, verbose_name='Descripción')),
                ('is_cover', models.BooleanField(default=False, help_text='Marcar como foto principal de la sucursal', verbose_name='Es portada')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Foto de sucursal',
                'verbose_name_plural': 'Fotos de sucursal',
                'ordering': ['-is_cover', 'order', '-created_at'],
            },
        ),
    ]
