# Generated by Django 5.2.9 on 2025-12-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branchphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('peluqueria', 'Peluquería'), ('barberia', 'Barbería'), ('unas', 'Uñas'), ('spa', 'Spa & Masajes'), ('estetica', 'Estética'), ('maquillaje', 'Maquillaje')], max_length=50, unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (ej: scissors, spa, nail)', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='bg-pink-100 text-pink-600', help_text='Clases de Tailwind para el color', max_length=50, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de negocio',
                'verbose_name_plural': 'Categorías de negocio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las categorías que aplican a este negocio', related_name='businesses', to='core.businesscategory', verbose_name='Categorías'),
        ),
    ]
