# Generated by Django 5.2.9 on 2025-12-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffmember_calendar_color'),
        ('appointments', '0002_initial'),
        ('core', '0004_add_business_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], help_text='Calificación de 1 a 5 estrellas', verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional sobre la experiencia', verbose_name='Comentario')),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si el cliente tuvo una cita verificada', verbose_name='Verificado')),
                ('is_approved', models.BooleanField(default=True, help_text='Las reseñas pueden ser moderadas', verbose_name='Aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='appointments.appointment', verbose_name='Cita relacionada')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.branch', verbose_name='Sucursal')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='accounts.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('client', 'appointment'), name='unique_review_per_appointment')],
            },
        ),
    ]
