# Generated by Django 5.2.9 on 2025-12-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('core', '0005_add_review_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('is_used', models.BooleanField(default=False, help_text='Se marca como usado cuando el cliente deja la reseña', verbose_name='Usado')),
                ('expires_at', models.DateTimeField(help_text='El token expira después de 7 días', verbose_name='Expira')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado el')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_token', to='appointments.appointment', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Token de reseña',
                'verbose_name_plural': 'Tokens de reseña',
                'ordering': ['-created_at'],
            },
        ),
    ]
