# Generated by Django 5.2.9 on 2025-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reviewtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_position',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical de la imagen (0=arriba, 50=centro, 100=abajo)', verbose_name='Posición de portada'),
        ),
    ]
