# Generated by Django 5.2.9 on 2026-05-11 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_cover_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='deposit_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje del precio cobrado al reservar (0-100). 0 = sin depósito.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de depósito'),
        ),
        migrations.AddField(
            model_name='branch',
            name='refund_window_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Si el cliente cancela con esta antelación, se reembolsa el depósito.', verbose_name='Horas antes para reembolso'),
        ),
    ]
