# Generated by Django 5.2.9 on 2025-12-13 19:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_staffmember_calendar_color'),
        ('core', '0006_reviewtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Plan Estándar', max_length=100, verbose_name='Nombre del plan')),
                ('price_per_staff', models.DecimalField(decimal_places=2, help_text='Precio mensual por cada profesional activo en el equipo', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por profesional/mes')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Días gratis al agregar un nuevo profesional al equipo', verbose_name='Días de prueba')),
                ('currency', models.CharField(default='PEN', help_text='Código ISO de la moneda (PEN, USD, etc.)', max_length=3, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Plan de precios',
                'verbose_name_plural': 'Planes de precios',
            },
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Período de prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='trial', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de suscripción')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del período de prueba')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima facturación')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Último pago')),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto último pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Suscripción de negocio',
                'verbose_name_plural': 'Suscripciones de negocios',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('staff_count', models.PositiveIntegerField(verbose_name='Cantidad de profesionales')),
                ('price_per_staff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por profesional')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('is_prorated', models.BooleanField(default=False, verbose_name='Es prorrateado')),
                ('prorated_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días prorrateados')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('currency', models.CharField(default='PEN', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada en')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Agregado al equipo')),
                ('trial_ends_at', models.DateTimeField(verbose_name='Fin de prueba')),
                ('is_billable', models.BooleanField(default=False, verbose_name='Es facturable')),
                ('billable_since', models.DateField(blank=True, null=True, verbose_name='Facturable desde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_subscriptions', to='core.business', verbose_name='Negocio')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_records', to='accounts.staffmember', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Suscripción de profesional',
                'verbose_name_plural': 'Suscripciones de profesionales',
                'unique_together': {('business', 'staff')},
            },
        ),
    ]
