# Generated by Django 5.2.9 on 2025-12-18 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffmember_calendar_color'),
        ('core', '0006_reviewtoken'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='invoice',
            name='max_payment_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Máx. intentos de cobro'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(help_text='Guardado para historial si el staff se elimina', max_length=200, verbose_name='Nombre del profesional')),
                ('period_start', models.DateField(verbose_name='Inicio período')),
                ('period_end', models.DateField(verbose_name='Fin período')),
                ('days_in_period', models.PositiveIntegerField(help_text='Total días del mes (28-31)', verbose_name='Días en período')),
                ('days_active', models.PositiveIntegerField(help_text='Días que el profesional estuvo activo/billable', verbose_name='Días activo')),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Precio mensual por profesional al momento de facturar', max_digits=10, verbose_name='Tarifa mensual')),
                ('daily_rate', models.DecimalField(decimal_places=4, help_text='monthly_rate / days_in_period', max_digits=10, verbose_name='Tarifa diaria')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='days_active × daily_rate', max_digits=10, verbose_name='Subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='subscriptions.invoice', verbose_name='Factura')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='accounts.staffmember', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culqi_customer_id', models.CharField(help_text='Customer ID en Culqi (cus_xxx)', max_length=100, verbose_name='ID Cliente Culqi')),
                ('culqi_card_id', models.CharField(help_text='Card ID en Culqi (crd_xxx)', max_length=100, verbose_name='ID Tarjeta Culqi')),
                ('card_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], default='credit', max_length=20, verbose_name='Tipo de tarjeta')),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('diners', 'Diners Club')], default='visa', max_length=20, verbose_name='Marca')),
                ('last_four', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('holder_name', models.CharField(max_length=100, verbose_name='Nombre del titular')),
                ('expiration_month', models.PositiveIntegerField(verbose_name='Mes expiración')),
                ('expiration_year', models.PositiveIntegerField(verbose_name='Año expiración')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('amount_cents', models.PositiveIntegerField(help_text='Culqi trabaja en céntimos (4650 = S/46.50)', verbose_name='Monto en céntimos')),
                ('currency', models.CharField(default='PEN', max_length=3, verbose_name='Moneda')),
                ('culqi_charge_id', models.CharField(blank=True, help_text='Charge ID (chr_xxx)', max_length=100, verbose_name='ID Cargo Culqi')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('culqi_response_code', models.CharField(blank=True, max_length=50, verbose_name='Código respuesta')),
                ('culqi_response_message', models.CharField(blank=True, max_length=200, verbose_name='Mensaje respuesta')),
                ('culqi_full_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta completa Culqi')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Número de intento')),
                ('is_automatic', models.BooleanField(default=True, help_text='True si fue por Celery, False si fue manual', verbose_name='Cobro automático')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.invoice', verbose_name='Factura')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.paymentmethod', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.paymentmethod', verbose_name='Método de pago usado'),
        ),
    ]
