# Generated by Django 5.2.9 on 2025-12-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_add_payment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscription',
            name='courtesy_reason',
            field=models.CharField(blank=True, help_text='Ej: Cliente beta, Promoción lanzamiento, Partner', max_length=200, verbose_name='Motivo cortesía'),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='courtesy_until',
            field=models.DateField(blank=True, help_text='Fecha límite del acceso cortesía (vacío = sin límite)', null=True, verbose_name='Cortesía hasta'),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='has_courtesy_access',
            field=models.BooleanField(default=False, help_text='Permite pagar facturas sin tarjeta real', verbose_name='Acceso cortesía'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('courtesy', 'Cortesía')], default='card', max_length=20, verbose_name='Tipo de método'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='brand',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('diners', 'Diners Club'), ('courtesy', 'Cortesía Stylo')], default='visa', max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(blank=True, choices=[('credit', 'Crédito'), ('debit', 'Débito')], default='credit', max_length=20, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='culqi_card_id',
            field=models.CharField(blank=True, help_text='Card ID en Culqi (crd_xxx)', max_length=100, verbose_name='ID Tarjeta Culqi'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='culqi_customer_id',
            field=models.CharField(blank=True, help_text='Customer ID en Culqi (cus_xxx)', max_length=100, verbose_name='ID Cliente Culqi'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mes expiración'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año expiración'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='holder_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del titular'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='last_four',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos'),
        ),
    ]
