# Generated by Django 5.2.9 on 2025-12-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_courtesy_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsubscription',
            name='deactivated_at',
            field=models.DateField(blank=True, help_text='Fecha en que el dueño desactivó al profesional', null=True, verbose_name='Desactivado el'),
        ),
    ]
