# Generated by Django 5.2.9 on 2025-12-08 23:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token de sesión')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono WhatsApp')),
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('last_name_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Género del cliente para filtrar servicios', max_length=1, verbose_name='Género')),
                ('branch_id', models.PositiveIntegerField(verbose_name='ID Sucursal')),
                ('service_id', models.PositiveIntegerField(verbose_name='ID Servicio')),
                ('staff_id', models.PositiveIntegerField(verbose_name='ID Profesional')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha/hora inicio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('otp_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash del OTP')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de datos'), ('OTP_SENT', 'OTP Enviado'), ('OTP_VERIFIED', 'OTP Verificado'), ('COMPLETED', 'Reserva Completada'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Máximo de intentos')),
                ('appointment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Cita creada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado')),
            ],
            options={
                'verbose_name': 'Sesión de Reserva',
                'verbose_name_plural': 'Sesiones de Reserva',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(blank=True, help_text='Formato internacional: +51987654321', max_length=20, null=True, unique=True, verbose_name='Número de teléfono')),
                ('email', models.EmailField(blank=True, help_text='Requerido para super_admin', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('business_owner', 'Dueño de Negocio'), ('branch_manager', 'Administrador de Sucursal'), ('staff', 'Profesional')], default='staff', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff Django')),
                ('is_verified', models.BooleanField(default=False, help_text='True cuando el usuario verificó su teléfono por OTP', verbose_name='Verificado')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('managed_branches', models.ManyToManyField(blank=True, related_name='managers', to='core.branch', verbose_name='Sucursales administradas')),
                ('owned_businesses', models.ManyToManyField(blank=True, related_name='owners', to='core.business', verbose_name='Negocios propios')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Cuenta de Negocio',
                'verbose_name_plural': 'Cuentas de Negocio',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('ce', 'Carné de Extranjería')], max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('last_name_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Teléfono de contacto del profesional', max_length=20, verbose_name='Teléfono')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Especialidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by_admin', models.BooleanField(default=False, help_text='True si fue creado por un admin y el staff no ha verificado su cuenta', verbose_name='Creado por admin')),
                ('branches', models.ManyToManyField(blank=True, related_name='staff_members', to='core.branch', verbose_name='Sucursales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['first_name'],
                'unique_together': {('document_type', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('otp_hash', models.CharField(max_length=64, verbose_name='Hash del OTP')),
                ('status', models.CharField(choices=[('OTP_SENT', 'OTP Enviado'), ('OTP_VERIFIED', 'OTP Verificado'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Expirado')], default='OTP_SENT', max_length=20, verbose_name='Estado')),
                ('registration_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de registro')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Máximo de intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado')),
                ('pending_staff_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_sessions', to='accounts.staffmember', verbose_name='Staff pendiente de vincular')),
            ],
            options={
                'verbose_name': 'Sesión de Login',
                'verbose_name_plural': 'Sesiones de Login',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('ce', 'Carné de Extranjería')], max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('last_name_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owners/photos/', verbose_name='Foto de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Dueño',
                'verbose_name_plural': 'Perfiles de Dueños',
                'unique_together': {('document_type', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('ce', 'Carné de Extranjería')], max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('last_name_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('phone_number', models.CharField(default='', help_text='Formato internacional: +51987654321', max_length=20, verbose_name='Número de teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Género del cliente para filtrar servicios disponibles', max_length=1, verbose_name='Género')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Foto de perfil')),
                ('whatsapp_opt_in', models.BooleanField(default=True, verbose_name='Acepta notificaciones WhatsApp')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('document_type', 'document_number')},
            },
        ),
    ]
