# Generated by Django 5.2.9 on 2025-12-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_branch_closing_time_branch_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='current_business',
            field=models.ForeignKey(blank=True, help_text='El negocio al que pertenece actualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.business', verbose_name='Negocio actual'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Activo'), ('released', 'Liberado'), ('pending', 'Pendiente')], default='pending', help_text='Estado actual del profesional en la plataforma', max_length=20, verbose_name='Estado de empleo'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando fue liberado del negocio anterior', null=True, verbose_name='Fecha de liberación'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='branch_staff', to='core.branch', verbose_name='Sucursales'),
        ),
        migrations.CreateModel(
            name='StaffEmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='Fecha cuando comenzó a trabajar en el negocio', verbose_name='Fecha de inicio')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Fecha cuando dejó de trabajar (null si aún trabaja)', null=True, verbose_name='Fecha de fin')),
                ('release_reason', models.TextField(blank=True, help_text='Motivo por el cual el dueño liberó al profesional', verbose_name='Motivo del release')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_history', to='core.business', verbose_name='Negocio')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_releases', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='accounts.staffmember', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Historial de Empleo',
                'verbose_name_plural': 'Historial de Empleos',
                'ordering': ['-started_at'],
            },
        ),
    ]
