# Generated by Django 5.2.9 on 2025-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_staff_employment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
