# Generated by Django 5.2.9 on 2025-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bookingsession_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='booking_sessions/photos/', verbose_name='Foto del cliente'),
        ),
    ]
