# Generated by Django 5.2.9 on 2025-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookingsession_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='calendar_color',
            field=models.CharField(default='#3B82F6', help_text='Color hexadecimal para identificar al profesional en el calendario', max_length=7, verbose_name='Color de calendario'),
        ),
    ]
