# Generated by Django 5.2.9 on 2025-12-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('break', 'Descanso'), ('training', 'Capacitación'), ('personal', 'Personal'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de bloqueo')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='accounts.staffmember', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Tiempo Bloqueado',
                'verbose_name_plural': 'Tiempos Bloqueados',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BranchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('opening_time', models.TimeField(verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de cierre')),
                ('is_open', models.BooleanField(default=True, verbose_name='Abierto')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Horario de Sucursal',
                'verbose_name_plural': 'Horarios de Sucursales',
                'ordering': ['branch', 'day_of_week'],
                'unique_together': {('branch', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('date_type', models.CharField(choices=[('holiday', 'Feriado'), ('special_hours', 'Horario especial'), ('closed', 'Cerrado')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to='core.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Fecha Especial',
                'verbose_name_plural': 'Fechas Especiales',
                'ordering': ['date'],
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('is_working', models.BooleanField(default=True, verbose_name='Trabaja')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='core.branch', verbose_name='Sucursal')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='accounts.staffmember', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['staff', 'branch', 'day_of_week'],
                'unique_together': {('staff', 'branch', 'day_of_week')},
            },
        ),
    ]
